language: node_js
node_js:
  - 'lts/*'

script: npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  fqdn: docs.greenhubproject.org
  on:
    branch: master
